name: CI

on:
  push:
    branches:
      - master
      - 'changeset-release/master'
  pull_request:
    paths:
      - .changeset/**
      - .github/workflows/ci.yml
      - 'projects/**'
      - 'jest/**'
      - 'package.json'
      - 'pnpm-workspace.yaml'
permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
        node_version: [14]
    name: ${{ matrix.os }} / Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install pnpm
        run: npm -g i pnpm@6.32.15 husky
      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install
        run: npm run deps
      - name: build
        run: npm run build && npm run npm_pack
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/
