name: publish
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches:
      - "master" # Run the workflow when pushing to the main branch
  pull_request:
    branches:
      - "*" # Run the workflow for all pull requests
  release:
    types:
      - published # Run the workflow when a new GitHub release is published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  REPOSITORY_URL: "https://github.com/${{ github.repository }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Get all history to allow automatic versioning using MinVer

      # Install the .NET SDK indicated in the global.json file
      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      # Build the solution
      - run: dotnet restore Seacraft.sln && dotnet build Seacraft.sln --configuration Release
        working-directory: ${{ github.workspace }}/engine

      # Publish the NuGet packages
      - name: Publish
        if: startsWith(github.ref, 'refs/heads/master')
        run: |
          dotnet nuget add source \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text \
            --name github \
            "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" && \
          dotnet nuget push "**/*.nupkg" --source 'github' --api-key ${{ secrets.GITHUB_TOKEN }}
